### ISSUE TITLE
Optimise images

### ISSUE THREAD

**Issue by achoo-o** [matai-2024/pawpals#54]
Reduce the image file size. This helps with webpage loading times, and therefore better UX.

## Guide - 
1. Go to (sqoosh.app)[https://squoosh.app/]
2. Drag or upload your image
3. In the bottom right, under 'compress', select 'Webp' from the dropdown list.
4. Use the compress slider to reduce file size further (don't make them horrible quality though!)
5. Once it has loaded, download the new image.
Double check the file is smaller/compressed and do it for each image. There are also some mass image compressors, however we don't have too many images in this project so it shouldn't take too long.

## Tasks
- [ ] Compress and convert the images to .webp format
- [ ] Change any '.jpg' usage in code to '.webp' so the project images load with the new filename
- [ ] I have checked multiple pages which use images and, after making my changes, they all load properly.
