### ISSUE TITLE
Update: Events list

### ISSUE THREAD

**Issue by anaherawashere** [matai-2024/pawpals#68]
**TODO:**
- [x] Dynamically render the attending count
- [x] Link each event card to their event details page
- [x] Add shadow to the card using `shadow-lg`
- [x] Add a hover state to the card, perhaps `hover: bg-gray-50` and `hover:shadow-xl`
- [x] Add `rounded-lg` to the div surrounding the image so it has softer corners
- [x] Move the address/location to the line with the date and time
- [x] Stretch: Address/location should just show the content before the second coma (street and suburb only)
- [x] Add space above the 'XX Attending' text, see Figma for spacing between text lines
- [x] Stretch: Is it possible to hide emojis from the description? They make the descriptions look a bit messy
- [x] Style the search input to look like the text inputs on the events form
- [x] Add a visible label to search input with text "Search events"
- [x] Change the description below the heading 'Pet-friendly Events' to:

"Looking for exciting pet-friendly events in your area? Whether it's a dog-friendly market, a pet costume party, or a neighbourhood pet birthday bash, we’ve got you covered! Discover local events where you and your furry friends can have a blast. Check out the latest pet events near you and make unforgettable memories with your best mate!"

**Styling consistency checklist:**
- [x] Remove any arbitrary values and use tailwind's nearest version including font-family, e.g. `w-[112px]` should be `w-28` and `font-[Inter]` can be removed
- [x] Remove `indigo` styles, replace with `gray` equivalent (unless it looks prettiest in yellow)
- [ ] _Optional_: Optimise for mobile (iPhone 12 Pro). Cards might need to change from horizontal to vertical

**Before pull request:**
- [x] Get Anahera to approve styling changes please
